export default {
    products: [{
        id: '123455',
        name: "thigh tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 15,
        numReview: 4.5,
        star: 10,
        countInStock: 0,
    },
    {
        id: '124455',
        name: "slim tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 15,
        numReview: 4.5,
        star: 10,
        countInStock: 6,
    },
    {
        id: '1234557',
        name: "slim tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 15,
        numReview: 4.5,
        star: 10,
        countInStock: 8,
    },
    {
        id: '143455',
        name: "slim tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 15,
        numReview: 4.5,
        star: 10,
        countInStock: 4,
    },
    {
        id: '1234558',
        name: "fit tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 65,
        numReview: 4.5,
        star: 10,
        countInStock: 4,
    },
    {
        id: '123458',
        name: "new tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 455,
        numReview: 4.5,
        star: 10,
        countInStock: 4,
    },
    {
        id: '123450',
        name: "narrow tshirs",
        image: '/images/d1.jpg',
        brand: "nike",
        price: 25,
        numReview: 4.5,
        star: 10,
        countInStock: 4,
    }
    ]
}